# -*- coding: utf-8 -*-
"""parphraser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lNb_kr26L1YpONVjeWJPqsdEIwoDULfd

# **AI-Powered Paraphrasing Tool using Transformers**
---
---

## Module End Assignment – Generative AI
### Author: Fathima Salga  
### Tools Used: Python, Hugging Face Transformers, PyTorch

##  Project Objective:
---

The goal of this project is to develop an AI-powered paraphrasing tool that:

- Takes input text
- Generates a paraphrased version
- Preserves semantic meaning
- Improves clarity and fluency
- Evaluates output quality using NLP metrics

This system is built using transformer-based deep learning models.

## **1. Introduction**
---

### What is Paraphrasing?

Paraphrasing is the process of rewriting text in a different way while preserving its original meaning.

It is widely used in:
- Content creation
- Plagiarism reduction
- Text summarization
- Academic writing
- Chatbots and conversational AI



### Why Use AI for Paraphrasing?

Traditional NLP models struggle with contextual understanding.

Transformers:
- Use self-attention mechanisms
- Understand context better
- Generate fluent text
- Process words in parallel
"""

!pip install transformers torch sentencepiece nltk rouge-score sentence-transformers language-tool-python

"""## **2. Transformer Architecture**
---

### What is a Transformer?

A Transformer is a deep learning model that uses:

- Self-attention mechanism
- Multi-head attention
- Encoder-decoder architecture

Unlike RNNs, transformers process all words simultaneously.



### Why T5 Model?

T5 (Text-To-Text Transfer Transformer):

- Treats every NLP task as text generation
- Converts tasks into text-to-text format
- Performs well in paraphrasing tasks

Example:
Input: "paraphrase: Artificial Intelligence is powerful."
Output: "AI is a powerful technology."
"""

# Import Essential Libraries
#----------------------------
import torch
from transformers import T5Tokenizer, T5ForConditionalGeneration
from rouge_score import rouge_scorer
from sentence_transformers import SentenceTransformer, util
import language_tool_python
import nltk

nltk.download('punkt')

"""## **3. Methodology**
---

1. Model Loading


2. Text Generation

##3.1 Model Loading

In this step, we load:

1. T5 Paraphrasing Model  
2. Sentence Transformer (for similarity scoring)  
3. LanguageTool (for grammar correction)  

We load a fine-tuned T5 paraphrasing model from Hugging Face.

Model Used:
- **ramsrigouthamg/t5_paraphraser**
"""

# Load Models
#-------------------

print("Loading models... Please wait.")

tokenizer = T5Tokenizer.from_pretrained("ramsrigouthamg/t5_paraphraser")
model = T5ForConditionalGeneration.from_pretrained("ramsrigouthamg/t5_paraphraser")

similarity_model = SentenceTransformer('all-MiniLM-L6-v2')
grammar_tool = language_tool_python.LanguageTool('en-US')

print("Models loaded successfully!")

"""##3.2 Text Generation Method

- Input Formatting

T5 requires task prefix: "paraphrase: <input_text> </s>"


- Beam Search

We use Beam Search decoding  for better output quality.:

     - num_beams = 5
     - max_length = 256
     - early_stopping = True

Beam Search improves output quality by exploring multiple possible sequences.
"""

# Paraphrasing Function
#---------------------------

def paraphrase_text(input_text_str):

    input_text = "paraphrase: " + input_text_str + " </s>"

    encoding = tokenizer(
        input_text,
        return_tensors="pt"
    )

    outputs = model.generate(
        input_ids=encoding["input_ids"],
        attention_mask=encoding["attention_mask"],
        max_length=256,
        num_beams=5,
        num_return_sequences=1,
        early_stopping=True
    )

    paraphrased = tokenizer.decode(outputs[0], skip_special_tokens=True)

    return paraphrased

"""##**4. Evaluation Metrics**
---

To measure the performance of the model, we use:

### 1. ROUGE Score
- ROUGE-1: Word overlap
- ROUGE-L: Longest sequence similarity

Higher score → Higher lexical similarity


### 2. Semantic Similarity

We compute cosine similarity between sentence embeddings.

Range: 0 to 1  
> 0.85 indicates strong meaning preservation


### 3. Grammar Correction

We use LanguageTool to:
- Detect grammatical errors
- Improve fluency
"""

# Evaluation Function
#-----------------------
def evaluate_text(original, paraphrased):

    # Grammar Correction
    matches = grammar_tool.check(paraphrased)
    corrected_text = language_tool_python.utils.correct(paraphrased, matches)

    # ROUGE Score
    scorer = rouge_scorer.RougeScorer(['rouge1', 'rougeL'], use_stemmer=True)
    rouge_scores = scorer.score(original, corrected_text)

    # Semantic Similarity
    embeddings = similarity_model.encode([original, corrected_text])
    similarity_score = util.cos_sim(embeddings[0], embeddings[1]).item()

    return corrected_text, rouge_scores, similarity_score

"""##**5. Model Testing**
---

Now we test the system using a sample input sentence.

The system will:

1. Generate paraphrased text  
2. Apply grammar correction  
3. Calculate evaluation scores  
4. Display results  
"""

# Run Example
#---------------
input_text = "Machine learning algorithms enable computers to learn and sudy from data and make predictions without being explicitly programmed."

paraphrased_output = paraphrase_text(input_text)

corrected_output, rouge_scores, similarity_score = evaluate_text(
    input_text, paraphrased_output
)

print("Original Text:\n", input_text)
print("\nParaphrased Text:\n", corrected_output)
print("\nROUGE Scores:\n", rouge_scores)
print("\nSemantic Similarity Score:\n", similarity_score)

"""##6. Results

The model successfully generates a paraphrased sentence while:

- Preserving meaning
- Maintaining grammatical correctness
- Achieving high semantic similarity

ROUGE scores show lexical overlap with variation,
while cosine similarity confirms semantic preservation.

---

##7. Conclusion

This project demonstrates how transformer-based models
can effectively perform paraphrasing tasks.

The integration of evaluation metrics ensures output quality and reliability.

---

## Future Improvements

- Fine-tune on custom dataset
- Add multiple paraphrase generation
- Deploy as web application
- Optimize performance using GPU
"""

